##
## >>chng 26 oct 05, from 100. to 172.0951, set initial monitor value
monitor grain temperature 01  172.0951
##
## >>chng 26 oct 05, from 100. to 165.7362, set initial monitor value
monitor grain temperature 02  165.7362
##
## >>chng 26 oct 05, from 100. to 155.5060, set initial monitor value
monitor grain temperature 03  155.5060
##
## >>chng 26 oct 05, from 100. to 144.1608, set initial monitor value
monitor grain temperature 04  144.1608
##
## >>chng 26 oct 05, from 100. to 132.3769, set initial monitor value
monitor grain temperature 05  132.3769
##
## >>chng 26 oct 05, from 100. to 120.5378, set initial monitor value
monitor grain temperature 06  120.5378
##
## >>chng 26 oct 05, from 100. to 109.2635, set initial monitor value
monitor grain temperature 07  109.2635
##
## >>chng 26 oct 05, from 100. to 98.7004, set initial monitor value
monitor grain temperature 08   98.7004
##
## >>chng 26 oct 05, from 100. to 89.0130 , set initial monitor value
monitor grain temperature 09   89.0130 
##
## >>chng 26 oct 05, from 100. to 80.1936, set initial monitor value
monitor grain temperature 10   80.1936
##
## >>chng 26 oct 05, from 100. to 129.9521, set initial monitor value
monitor grain temperature 11  129.9521
##
## >>chng 26 oct 05, from 100. to 127.3672, set initial monitor value
monitor grain temperature 12  127.3672
##
## >>chng 26 oct 05, from 100. to 122.8204, set initial monitor value
monitor grain temperature 13  122.8204
##
## >>chng 26 oct 05, from 100. to 116.9125, set initial monitor value
monitor grain temperature 14  116.9125
##
## >>chng 26 oct 05, from 100. to 110.0613, set initial monitor value
monitor grain temperature 15  110.0613
##
## >>chng 26 oct 05, from 100. to 102.5874, set initial monitor value
monitor grain temperature 16  102.5874
##
## >>chng 26 oct 05, from 100. to 95.2020, set initial monitor value
monitor grain temperature 17   95.2020
##
## >>chng 26 oct 05, from 100. to 88.2345, set initial monitor value
monitor grain temperature 18   88.2345
##
## >>chng 26 oct 05, from 100. to 81.8415, set initial monitor value
monitor grain temperature 19   81.8415
##
## >>chng 26 oct 05, from 100. to 76.0553, set initial monitor value
monitor grain temperature 20   76.0553
##
## >>chng 26 oct 05, from 10. to 2.8239, set initial monitor value
monitor grain potential 01  2.8239
##
## >>chng 26 oct 05, from 10. to 2.7356, set initial monitor value
monitor grain potential 02  2.7356
##
## >>chng 26 oct 05, from 10. to 2.3843, set initial monitor value
monitor grain potential 03  2.3843
##
## >>chng 26 oct 05, from 10. to 1.9782, set initial monitor value
monitor grain potential 04  1.9782
##
## >>chng 26 oct 05, from 10. to 1.5850, set initial monitor value
monitor grain potential 05  1.5850
##
## >>chng 26 oct 05, from 10. to 1.2303, set initial monitor value
monitor grain potential 06  1.2303
##
## >>chng 26 oct 05, from 10. to 0.9413, set initial monitor value
monitor grain potential 07  0.9413
##
## >>chng 26 oct 05, from 10. to 0.7221, set initial monitor value
monitor grain potential 08  0.7221
##
## >>chng 26 oct 05, from 10. to 0.5649, set initial monitor value
monitor grain potential 09  0.5649
##
## >>chng 26 oct 05, from 10. to 0.4557, set initial monitor value
monitor grain potential 10  0.4557
##
## >>chng 26 oct 05, from 10. to 1.0635, set initial monitor value
monitor grain potential 11  1.0635
##
## >>chng 26 oct 05, from 10. to 1.1234, set initial monitor value
monitor grain potential 12  1.1234
##
## >>chng 26 oct 05, from 10. to 1.0595, set initial monitor value
monitor grain potential 13  1.0595
##
## >>chng 26 oct 05, from 10. to 0.9056, set initial monitor value
monitor grain potential 14  0.9056
##
## >>chng 26 oct 05, from 10. to 0.7051, set initial monitor value
monitor grain potential 15  0.7051
##
## >>chng 26 oct 05, from 10. to 0.5040, set initial monitor value
monitor grain potential 16  0.5040
##
## >>chng 26 oct 05, from 10. to 0.3281, set initial monitor value
monitor grain potential 17  0.3281
##
## >>chng 26 oct 05, from 10. to 0.1888, set initial monitor value
monitor grain potential 18  0.1888
##
## >>chng 26 oct 05, from 10. to 0.0863, set initial monitor value
monitor grain potential 19  0.0863
##
## >>chng 26 oct 05, from 10. to 0.0139, set initial monitor value
monitor grain potential 20  0.0139
##
## >>chng 26 oct 05, from 15. to 20.0251, set initial monitor value
monitor line luminosity "GrGH" 0  20.0251
##
## >>chng 26 oct 05, from 15. to 19.4129, set initial monitor value
monitor line luminosity "GrCC" 0  19.4129
##
## >>chng 26 oct 05, from 15. to 21.1983, set initial monitor value
monitor line luminosity "GraI" 0  21.1983
##
## >>chng 26 oct 05, from 15. to 21.2520, set initial monitor value
monitor line luminosity "GraT" 0  21.2520
##
## >>chng 26 oct 05, from 15. to 20.3163, set initial monitor value
monitor line luminosity "GraC" 0  20.3163
##
## >>chng 26 oct 05, from 15. to 17.7698, set initial monitor value
monitor line luminosity "GraD" 0  17.7698
##
## >>chng 26 oct 05, from 15. to 17.7745, set initial monitor value
monitor line luminosity "GraL" 1215.67A  17.7745
